spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa # database connection url
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # application 로딩 시점 table ddl
    properties:
      hibernate:
#        show_sql: true # Hibernate가 DB에 날리는 모든 쿼리 표출 (출력창)
        format_sql: true # 한줄로 출력되는 SQL formattin

# Pageable 글로벌 세팅
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
#        one-indexed-parameters: true
        # 1부터 시작하는 index parameter Page 객체는 기본적으로 0부터 시작하기 떄문
        # url에 page=1 list 뿌려주는 것은 잘 뿌려주는데 반환되는 pageable 객체는 그대로 0으로 가져가는 한계가 있음

logging:
  level:
    org.hibernate.sql: DEBUG # DB에 날리는 쿼리 로그 파일
#    org.hibernate.type: trace # 쿼리 파라미터 바인딩 => p6spy 외부라이브러리 사용