spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa # database connection url
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # application 로딩 시점 table ddl
    properties:
      hibernate:
#        show_sql: true # Hibernate가 DB에 날리는 모든 쿼리 표출 (출력창)
        format_sql: true # 한줄로 출력되는 SQL formattin


logging:
  level:
    org.hibernate.sql: DEBUG # DB에 날리는 쿼리 로그 파일
#    org.hibernate.type: trace # 쿼리 파라미터 바인딩 => p6spy 외부라이브러리 사용